//! Parity test: Rust OCR core vs Python reference fixtures.
//!
//! Fixtures are generated by the production Python path
//! (`local_server/tests/parity/gen_reference.py`, bead-train env) and
//! contain per-cell: letterboxed input, ONNX logits, final code+confidence.
//! This test re-runs the same math through the Rust pipeline and asserts
//! bit-close agreement — the local-server runtime's conversion gate.
//!
//! Paths: BEAD_ARTIFACT_DIR / BEAD_PARITY_FIXTURES env vars override the
//! defaults below.

use std::path::{Path, PathBuf};

use bead_local_server::ocr::decode::{build_code_trie, constrained_decode, greedy_conf, log_softmax};
use bead_local_server::ocr::preprocess::{crop_cell_letterbox, hwc48_to_chw};
use bead_local_server::ocr::OnnxModel;
use serde::Deserialize;

const DEFAULT_ARTIFACT: &str =
    "D:/projects/python/ai_dou/artifacts/models/bean-mard-v10-2026-08-09T04-30-00Z";
const DEFAULT_FIXTURES: &str = "D:/projects/python/ai_dou/.scratch/parity-fixtures";
const REPO_ROOT: &str = "D:/projects/python/ai_dou";

#[derive(Deserialize)]
struct ReferenceCell {
    label: String,
    code: String,
    conf: f32,
    prep: Vec<f32>,
    logits: Vec<f32>,
}

#[derive(Deserialize)]
struct LibraryEntry {
    code: String,
    #[serde(default)]
    brand: Option<String>,
}

fn load_mard_codes() -> Vec<String> {
    let path = Path::new(REPO_ROOT).join("artifacts/colors/library.json");
    let entries: Vec<LibraryEntry> =
        serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    entries
        .into_iter()
        .filter(|e| e.brand.as_deref() == Some("mard"))
        .map(|e| e.code)
        .collect()
}

fn fixture_dir() -> PathBuf {
    std::env::var("BEAD_PARITY_FIXTURES")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(DEFAULT_FIXTURES))
}

fn artifact_dir() -> PathBuf {
    std::env::var("BEAD_ARTIFACT_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(DEFAULT_ARTIFACT))
}

#[test]
fn parity_with_python_reference() {
    let fixtures = fixture_dir();
    let reference_path = fixtures.join("reference.json");
    assert!(
        reference_path.exists(),
        "fixtures missing at {fixtures:?} — run: \
         python local_server/tests/parity/gen_reference.py"
    );
    let reference: std::collections::HashMap<String, ReferenceCell> =
        serde_json::from_str(&std::fs::read_to_string(&reference_path).unwrap()).unwrap();
    assert!(!reference.is_empty(), "empty reference");
    assert!(
        reference.len() >= 64,
        "expected >= 64 fixtures, got {} (run gen_reference.py with more sets)",
        reference.len()
    );

    let mut model = OnnxModel::load(&artifact_dir()).unwrap();
    eprintln!("DBG loaded model: {}", model.artifact_id);
    let mard_codes = load_mard_codes();
    assert!(mard_codes.len() > 100, "mard codes unexpectedly small");
    // Same closed vocabulary as gen_reference.py: mard codes (alpha+digits) + BLANK.
    let mut trie_codes: Vec<String> = mard_codes
        .iter()
        .filter(|c| {
            let mut cs = c.chars();
            cs.next().is_some_and(|ch| ch.is_ascii_alphabetic())
                && c.get(1..).is_some_and(|s| !s.is_empty() && s.bytes().all(|b| b.is_ascii_digit()))
        })
        .cloned()
        .collect();
    trie_codes.push("BLANK".into());
    trie_codes.sort();
    trie_codes.dedup();
    let trie = build_code_trie(&trie_codes);

    // Preprocess all cells, then ONE batch-N forward — identical execution
    // shape to gen_reference.py (batch-N onnxruntime numerics). Mixing batch
    // sizes produces 0.02-level logit drift on batch-1 LSTM kernels.
    let mut preps: Vec<Vec<f32>> = Vec::with_capacity(reference.len()); // CHW 0-1
    let mut preps_hwc: Vec<Vec<f32>> = Vec::with_capacity(reference.len()); // HWC 0-255
    let mut names: Vec<String> = reference.keys().cloned().collect();
    names.sort();
    for name in &names {
        let img_path = fixtures.join("cells").join(format!("{name}.png"));
        let img = image::ImageReader::open(&img_path)
            .unwrap()
            .decode()
            .unwrap()
            .to_rgb8();
        let (w, h) = (img.width() as usize, img.height() as usize);
        let mut rgb = vec![0f32; w * h * 3];
        for (i, px) in img.pixels().enumerate() {
            rgb[i * 3] = px[0] as f32;
            rgb[i * 3 + 1] = px[1] as f32;
            rgb[i * 3 + 2] = px[2] as f32;
        }
        let prep = crop_cell_letterbox(&rgb, w, h, 0, 0, w, h, 48);
        preps_hwc.push(prep.clone());
        preps.push(hwc48_to_chw(&prep));
    }
    let mut flat = vec![0f32; preps.len() * 3 * 48 * 48];
    for (bi, p) in preps.iter().enumerate() {
        flat[bi * 3 * 48 * 48..(bi + 1) * 3 * 48 * 48].copy_from_slice(p);
    }
    let logits_all = model.forward(&flat, preps.len()).unwrap();
    let n_classes = model.chars.len();
    let t = logits_all.len() / (preps.len() * n_classes);
    let log_probs = log_softmax(&logits_all, t, preps.len(), n_classes);
    let decoded = constrained_decode(
        &log_probs, t, preps.len(), n_classes, &trie, &model.char_to_idx, 0, 0.0,
    );
    let (greedy_codes, greedy_confs) =
        greedy_conf(&log_probs, t, preps.len(), n_classes, &model.chars);

    let mut max_prep_diff = 0f32;
    let mut max_logit_diff = 0f32;
    let mut max_conf_diff = 0f32;
    let mut code_mismatches = 0usize;
    let mut n = 0usize;

    for (idx, name) in names.iter().enumerate() {
        let ref_cell = &reference[name];
        // 1) Preprocessing parity (letterbox vs reference prep).
        for (a, b) in preps_hwc[idx].iter().zip(ref_cell.prep.iter()) {
            max_prep_diff = max_prep_diff.max((a - b).abs());
        }
        // 2) Logits parity (batch-N Rust forward vs batch-N Python reference).
        // (T, B, C) layout: sample idx is strided, not contiguous.
        let mut logits_i = Vec::with_capacity(t * n_classes);
        for tt in 0..t {
            let base = (tt * preps.len() + idx) * n_classes;
            logits_i.extend_from_slice(&logits_all[base..base + n_classes]);
        }
        for (a, b) in logits_i.iter().zip(ref_cell.logits.iter()) {
            max_logit_diff = max_logit_diff.max((a - b).abs());
        }
        // 3) Decode parity — same merge rules as ocr_cells_from_crop.
        let (mut code, score) = decoded[idx].clone();
        let greedy_code = &greedy_codes[idx];
        if !trie_codes.contains(&code) && trie_codes.contains(greedy_code) {
            code = greedy_code.clone();
        }
        let conf = if greedy_code == &code {
            greedy_confs[idx]
        } else {
            (score / t.max(1) as f32).exp()
        };
        if code != ref_cell.code {
            code_mismatches += 1;
            eprintln!(
                "  code mismatch {name}: rust={code:?} ref={} (label={})",
                ref_cell.code, ref_cell.label
            );
        }
        max_conf_diff = max_conf_diff.max((conf - ref_cell.conf).abs());
        n += 1;
    }

    println!("cells checked: {n}");
    println!("max prep diff (0-255 space): {max_prep_diff:.4}");
    println!("max logit diff: {max_logit_diff:.6}");
    println!("max conf diff: {max_conf_diff:.6}");
    println!("code mismatches: {code_mismatches}");

    // Thresholds — batch-N numerics are bit-close to the Python reference
    // (the acceptance gate locks final metrics; these catch gross divergence).
    // prep 0.5 = cv2-vs-weighted-area rounding (pre-quantization), expected.
    assert!(max_prep_diff < 1.0, "preprocessing drift: {max_prep_diff}");
    assert!(
        max_logit_diff < 0.05,
        "logits drift beyond tolerance: {max_logit_diff}"
    );
    assert!(max_conf_diff < 0.01, "confidence drift: {max_conf_diff}");
    assert_eq!(code_mismatches, 0, "{code_mismatches} decode mismatches");
}
