"""add pixel_color

Revision ID: 99c34497d51e
Revises: 5f306ae95079
Create Date: 2026-05-13 23:11:48.137438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c34497d51e'
down_revision: Union[str, Sequence[str], None] = '5f306ae95079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprint_cells', sa.Column('pixel_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blueprint_cells', 'pixel_color')
    # ### end Alembic commands ###
